spring.application.name=slowapi

# Server Port Configuration
server.port=8081

# H2 datasource
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./db_bank
spring.datasource.driver-class-name=org.h2.Driver

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger/OpenAPI
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.enabled=true
