spring.application.name=reactiveapi
# Server Port Configuration
server.port=8082

spring.datasource.username = sa
spring.datasource.password =
spring.datasource.url = jdbc:h2:file:./reactive_db
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect
spring.h2.console.enabled = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show_sql = true

# External API URL
api.external.url=http://localhost:8080

